version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/node.dockerfile
    container_name: ${REACT_APP_NAME}-react
    ports:
      - '${DOCKER_APP_PORT:-3001}:3000'
#      - "444:443"      # Port mapping for SSL traffic
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run start:dev